// eslint-disable-next-line import/prefer-default-export
export const athlonNames = new Map<number | undefined, string>([
	[0, 'Medenathlon'],
	[1, 'Monoathlon'],
	[2, 'Duathlon'],
	[3, 'Triathlon'],
	[4, 'Tetrathlon'],
	[5, 'Pentathlon'],
	[6, 'Hexathlon'],
	[7, 'Heptathlon'],
	[8, 'Octathlon'],
	[9, 'Enneathlon'],
	[10, 'Decathlon'],
	[11, 'Hendecathlon'],
	[12, 'Dodecathlon'],
	[13, 'Triadecathlon'],
	[14, 'Tessaradecathlon'],
	[15, 'Pentedecathlon'],
	[16, 'Hexadecathlon'],
	[17, 'Heptadecathlon'],
	[18, 'Octodecathlon'],
	[19, 'Enneadecathlon'],
	[20, 'Icosathlon'],
]);
