name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Firebase Configuration

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --except hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSG_DECATHLON }}'
