name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Firebase Configuration

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: deploy --except hosting
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
